const UI = {
  //  Filter
  MORE: 'more',
  SHOW: 'Show',
  RESET: 'Reset',
  FILTER: 'Filter',
  SHOWING_RESULT_FOR: 'Showing result for',
  JOBS: 'Jobs',
  REMARKS: 'Remarks',
  COOKIES_POLICY: 'Cookie policy',
  EMPLOYER_PROFILE: 'Employer profile',
  COOKIES_MSG:
    'We use cookies to ensure that you get the best experience on our website. By continuing to use this site, you give your consent to our',
  DEGREE: 'Degree',
  APPLICABLE_WHEN_PROFILE_IS_UPDATED: 'Applicable when profile is updated',
  VALIDITY: 'Validity',
  NEXT_ATTEMPT: 'Next Attempt',
  MATCHING: 'Matches',
  SEARCH_ON: 'Searched',
  RECENT_SEARCHES: 'My Recent Searches',
  CONTACT_PERSON: 'Contact person',
  APPLIED_JOBS: 'Applied Jobs',
  AUTO_APPLIED_BY_EMPLOYER: 'Auto Applied By Employer',
  CANDIDATES_FOR_JOB: 'Candidates for Job',
  PAGE_NOT_FOUND:
    'This space is blank right now, but every story began with a blank page.', // TBD - 'Page not Found...',
  PAGE_NOT_FOUND1:
    'Nothing here yet, but every painting was once a blank canvas', // TBD - there can be multiple such options to be shown to the user...'Page not Found...',
  //  Guidelines
  START: 'Start',
  GENERAL_INSTRUCTION: 'General Instructions',
  TERMS_CONDITIONS: 'Terms & Conditions',
  GUIDELINE_INSTRACTION: 'I have read all the instructions and agree to the',
  ASSESSMENT_INSTRUCTION: 'Assessment Instructions',

  //  Assessment
  NOT_PASSED: 'Not passesd',
  NO_RESULT: 'No result',
  ATTEMPTS_HISTORY: 'Attempts History',
  COMPLETED: 'Completed',
  COMPLETE: 'Complete',
  FOUND: 'found',
  AVAILABLE: 'Available',
  ANY: 'Any',
  REMANING_TIME: 'Remaining time',
  TIME_SPENT_ON_THIS_QUESTION: 'Time spent on this question',
  READ_TO_INSTRUCTIONS: 'Read instructions',
  END_TEST: 'End Test',
  SHOW_TO_EMPLOYER: 'Showcase this badge', // TBD 'Show to employer'
  YOUR_SKILL_RATING: 'Your current skill level is',
  SUBMIT_SUCCESSFUL: 'Your Assessment has been submitted successfully',
  YOUR_SCORE_IS_VERY_LESS:
    'You made a good attempt, but a little more effort will help you improve your rating. An improved rating will increase your chances of getting hired. We suggest you study the relevant topics thoroughly and re-assess yourself after 30 days.', // 'Your score is very low and he is not even in the category of Beginner, You have not crossed the cut-off set by us, so your ratings will not be visible to the employers. Please give assessment again after 30 days.'
  ASSESSMENT: 'Assessment',
  SAVE_SUBMIT: 'Save & Submit',
  SAVE_NEXT: 'Save & Next',
  SEC: 'sec',
  APPROX_TIME: 'Approximate time you should spend on this question',
  PLEASE_SELECT_AN_ANY_OPTION: 'Please select an option.',
  RE_ATTEMPT: 'Re-Attempt',
  NEED_IMPROVEMENT: 'Needs improvement',
  SKILL_RATING: 'Rating',

  START_TEST: ' Start Test',
  NUMBER_OF_QUESTIONS: 'Question Number', // As the context is showing question # out of total number so Number of Question is incorrect
  QUESTIONS: 'Questions',
  TIME: 'Time',
  MIN: 'min',
  TOTAL_ASSESSMENT_FOUND: 'Total assessments found',
  SKILL_TYPE: 'Skill Type',
  AVAILABLE_ASSESSMENT: 'Available Assessment',
  GREAT_START:
    'Great start, but time has run out. You won’t be able to attempt the rest of the assessment this time. Please re-assess yourself after a few weeks.', // 'Great start, but your time is up so are not able to answer remaing questions.',
  GENERATE_REPORT: 'Generate Report',
  RETRY_AFTER_30_DAYS: 'Retry after 30 days', // TBD: Need to remove hardcoding
  CLOSE: 'Close',
  YOU_ARE_GOING_TO_SUBMIT_ASSESSMENT:
    'You are going to submit this assessment, Once submitted your result will be generated.', // TBD - Context not clear… It requires changes

  ASSESSMENT_CONFIRM: 'Do you want to take the assessment?',
  DO_YOU_WANT_TO_CONFIRM: 'Do you want to confirm?',
  HOLD_ON: 'Hold on.',
  FLIP_QUESTIONS: 'Flipped questions',
  QUESTIONS_REMAINING: 'questions are remaining.',
  SURE_SUBMIT_ASSESSMENT: 'Are you sure you want to submit this assessment?',
  SUBMIT_ASSESSMENT: 'Submit Assessment',
  YES: 'Yes',
  NO: 'No',
  END_ASSESSMENT_TITLE: 'End Assessment',
  SURE_END_ASSESSMENT: 'Are you sure you want to end this assessment?',
  FLIP_THE_QUESTIONS: 'Flip the Question',
  FLIP_THIS_QUESTIONS: 'Flip this Question',
  SURE_FLIP_QUESTION: 'Are you sure you want to flip this question?',
  //  Summary List
  PAGE: 'Page',
  RESULTS: 'Results',
  SORT_BY: 'Sort by',
  OF: 'of',
  RELEVANCE: 'Relevance',

  //  Posted Jobs
  MATCHING_CANDIDATES: 'Matching Candidates',
  APPLIED_CANDIDATES: 'Applicants',
  PUBLISHED: 'Published',
  STATUS: 'Status',
  UPDATED: 'Updated',
  PRE_REQUISITES: 'Pre-Requisites',

  //  Transaction Status
  BANK_TRANSACTION_ID: 'Bank transaction Id',
  GATEWAY_TRANSACTION_ID: 'Gateway transaction Id',
  ORDERID: 'Order ID',
  TRANSACTION_TIME: 'Transaction time',
  AMOUNT: 'Amount',
  MESSAGE: 'Message',
  OK: 'OK',

  //  Buy Credit Points
  BUY_CREDIT: 'Buy Credit Points',
  ENTER_AMOUNT: 'Enter Amount',
  POINTS_WILL_BE_ADDED: 'Equivalent to points',
  APPLY_DISCOUNT_CODE: 'Apply Discount Code',
  PLACEHOLDER_DISCOUNT_CODE: 'Enter discount code',
  OPTIONAL: '(optional)',
  BUTTON_NEXT: 'Next',

  //  Point Summary
  CREDIT_POINTS: 'Credit Points',
  PROFILE: 'Profile',
  POINTS: 'Points',
  AVAILABLE_POINTS: 'Available Points',
  BUY_POINTS: 'Buy Points',
  FREE_POINTS: 'Free Points',
  REDEEM_FREE_POINTS: 'Redeem coupon',
  FREE_CODE_PLACEHOLDER: 'Enter coupon code',
  APPLY_BUTTON: 'Apply',

  //  Price Details
  PAYMENT_STATUS: 'Payment Status',
  PRICE_DETAILS: 'Payment Details',
  TOTAL: 'Total',
  TOTAL_PAYABLE_AMOUNT: 'Total Payable Amount',
  BACK_BUTTON: 'Back',
  MAKE_PAYMENT: 'Make Payment',
  FAILED: 'Payment Failed',
  SUCCESSFUL: 'Payment Successful',
  TRY_AGAIN: 'Try Again',

  //  Transaction History
  VIEW_TRANSACTION_HISTORY: 'View Transaction History',
  TRANSACTION_TYPE: 'Transaction Type',

  DETAILS: 'Details',
  POSTED_JOB: 'Posted Job',
  SELECT_OPTION: '--select--',
  PLACEHOLDER_CITY: 'Select city',
  MINIMUM_SALARY: 'Minimum',
  MAXMIMUM_SALARY: 'Maximum',
  ANY_SALARY: 'Open for discussion',
  PER_ANNUN: ' PA',
  //  Candidate Steps
  LOCATION: 'Location',
  DESIRED: 'Desired',
  REQUIRES: 'Requires',
  FRESHER: 'Fresher',
  ANY_LOCATION: 'Any Location',
  YEAR: 'year',
  DESIRED_LOCATION: 'Desired Location',
  PERSONAL_INFORMATION: 'Personal Information',
  DESIRED_JOBS: 'Desired Jobs',
  SKILLS: 'Skills',
  EDUCATION: 'Education',
  JOB_HISTORY: 'Job History',
  BREAK: 'Break',
  TOOLS: 'Tools',
  TOOL: 'Tool',
  CERTIFICATIONS: 'Certifications',
  OTHER: 'Other',
  SCHOOLING: 'Schooling',
  TO_UNLOCK: 'to Unlock',
  DOWNLOAD_RESUME: 'Download Resume',
  DELETE_RESUME: 'Delete Resume',
  DOWNLOAD_ID_PROOF: 'Download ID Proof',
  DELETE_ID_PROOF: 'Delete ID Proof',
  //  Company profile
  COMPANY_DETAILS: 'Company details',
  CONTACT_DETAILS: 'Contact details',
  EMPLOYER_JOBS: 'Employer jobs',
  OTHER_DETAILS: 'Other details',
  //  Post jobs
  ALT_LESS_RATING: 'Less rating',
  JOB_DETAILS: 'Job Details',
  SKILLS_AND_EXPERIENCE: 'Skills and Experience',
  POSTED: 'Posted',
  FULL_NAME: 'Full name',
  EMAIL: 'Email',
  MOBILE: 'Mobile',
  MOBILE_NUMBER: 'Mobile number',
  DATE_OF_BIRTH: 'Date of birth',
  GENDER: 'Gender',
  PASSPORT_NUMBER: 'Passport number',
  CITY: 'City',
  ADDRESS: 'Address',
  ENTER_YOUR_ADDRESS: 'Enter your address',
  ABOUT: 'About',
  PLACEHOLDER_ABOUT: 'Write a short introduction about yourself',
  RESUME: 'Resume',
  ID_PROOF: 'Photo Identity proof',
  OPEN_TO_WORK_AT_ANY_LOCATION: 'Open to work at any location',
  JOB_LOCATIONS: 'Job location(s)',
  JOB_LOCATION: 'Current Job location',
  EXPERIENCE: 'Experience',
  IN_MONTHS: 'in months',
  JOB_TYPE: 'Job type',
  WORK_LOCATION: 'Mode of Work',
  NEGOTIABLE: 'Negotiable',
  ARE_YOU_A_FRESHER: 'I am a fresher',
  DESIRED_SALARY: 'Desired Salary (PA)',
  WORK_EXPERIENCE_IN_YEAR: 'Work experience in year(s)',
  SHIFT: 'Shift',
  WHEN_CAN_YOU_JOIN: 'When can you join',
  WILLINGNESS_TO_RELOCATE: 'Willingness to relocate',
  EXPECTED_SALARY: 'Expected Salary',
  RATING: 'Rating',
  WHERE: 'Where',
  LAST_USED: 'Last used',
  TOOLS_PLACEHOLDER: 'Tool e.g. Eclipse, UML, Excel, Gitlab, Postman etc',
  COLLEGE_UNIVERSITY: 'College/University',
  COLLEGE: 'College',
  COURSE: 'Course',
  FROM: 'From',
  DATE_PLACEHOLDER: '01/01/2022',
  TO: 'To',
  AT_PRESENT: 'Ongoing',
  PERCENTAGE: 'Percentage (%)',
  PERCENTAGE_NAME: 'Percentage',
  PERCENT_SIGN: '%',
  UPLOADED_ON: 'Uploaded on ',
  REMOVE: 'Remove',
  REMOVE_PHOTO: 'Remove Photo',
  PHOTO: 'Photo',
  UPLOAD: 'Upload',
  SUPPORTED_FORMATS: 'Supported formats: ',
  CGPA: 'CGPA',
  WORK_EXPERIENCE: 'Employment',
  JOB_TITLE: 'Job title',
  TITLE: 'Title',
  COMPANY_NAME: 'Company Name',
  COMPANY: 'Company',
  CTC: 'CTC (PA)',
  CTC_PLACEHOLDER: 'CTC',
  ROLES_RESPONBILITIES: 'Roles/Responsibilities',
  REASON: 'Reason',
  VISIBILITY: 'Visible to the employer',
  NAME: 'Name',
  DESCRIPTION: 'Description',
  DATE: 'Date',
  VALIDITY_IN_MONTHS: 'Validity in months',
  ACHIEVEMENTS: 'Achievements',
  ACADEMIC_EXCELLENCE: 'Academic excellence',
  OPEN_SOURCE_COMMUNITY_CONTRIBUTION: 'Open source community contribution',
  PROJECTS: 'Projects',
  HOBBIES: 'Hobbies',
  PATENTS: 'Patents',
  LANGUAGE: 'Language',
  PROFILE_LINK: 'Profile link',
  LINKEDIN_LINK: 'Linkedin link',
  GITHUB_LINK: 'GitHub link',
  ONLINE_PROFILE_URL: 'Online profile URL',
  LINKEDIN: 'LinkedIn',
  GITHUB: 'GitHub',
  SCHOOL_NAME: 'Name of School',
  CLASS_NAME: 'Class',
  BOARD: 'Board',
  SAVE_AS_DRAFT: 'Save As Draft',
  POST_JOB: 'Post Job',
  CANDIDATE_COMPLETE_PROFILE_AND_INCREASE:
    'Complete profile and increase chances of getting hired',
  EMPLOYER_COMPLETE_PROFILE_AND_INCREASE:
    'Complete profile to hire the best talent instantly',

  POST_JOBS_PROFILE_MSG: 'Post jobs for enhanced visibility to the best talent',

  BACK: 'Back',
  NEXT: 'Next',
  POINT: 'credit point', // TBD - assuming that it will be shown as part of “Requires <1> point”
  JOB_DESCRIPTION: 'Job description',
  MINIMUM_QUALIFICATION: 'Minimum qualification',
  SALARY: 'Salary',
  OVERALL_EXPERIENCE: 'Overall experience',
  SKILLS_EXPERIENCE: 'Skills Experience',
  SKILL: 'Skill',
  NUMBER_OF_OPENINGS: 'Number of opening(s)',
  NUMBER_OF_OPENING: 'Number of opening',
  ALWAYS_HIRING: 'Always hiring',
  START_DATE: 'Start date',
  JOB_DEADLINE: 'Job deadline',
  JOB_EXPIRES_ON: 'Job expires on',
  PAY_BENEFITS: 'Pay benefits',
  OTHER_BENEFITS: 'Other benefits',
  UPDATE_PROFILE: 'Update Profile',
  YOUR_PROFILE_UPDATED: 'Your profile was updated',
  COMPANY_PROFILE: 'Company profile',
  LOGO: 'Logo',
  COMPANY_EMAIL_ID: 'Company email ID',
  COMPANY_TAGLINE: 'Company tagline',
  COMPANY_BRIEF: 'Company brief',
  GSTIN: 'GSTIN',
  FOUNDED_ON: 'Founded in',
  CONTACT_NAME: 'Contact person',
  CONTACT_NUMBER: 'Contact number',
  WEBSITE: 'Website',
  COMPANY_SIZE: "Company's headcount",
  COMPANY_STAGE: 'Company stage',
  FUNDING: 'Funding status',
  ENGINEERS_SIZE: "Engineers' headcount",
  TECHNOLOGY_STACK: 'Technology stack',
  HOW_DID_YOU_HEAR_ABOUT_US: 'How did you hear about us?',
  PLEASE_MENTION_HERE: 'Please mention here',
  FACEBOOK: 'Facebook',
  FACEBOOK_LINK: 'Facebook link',
  TWITTER: 'Twitter',
  TWITTER_LINK: 'Twitter link',

  ENTER_OPENING: 'Enter opening(s)',
  GST_NO: 'GST No',
  SELECT_THE_MONTH_YEAR: 'Select the month-year',
  COMPANY_ADDRESS: 'Company address',
  WWW_EXAMPLE_COM: 'www.example.com',
  HEAROTHERS: 'From where did you hear about us',
  ENTER_A_REASON: 'Enter a reason',
  IN_MONTH: 'In month(s)',
  ENTER: 'Enter %',
  ENTER_CGPA: 'Enter CGPA',
  SEARCH_CITY: 'Search City',
  ENTER_DESIRED_SALARY: 'Enter Desired salary',
  IN_YEAR: 'In year(s)',
  PLEASE_SELECT_CORRECT_DATES: 'please select correct dates',
  ADD: 'Add',
  UPDATE: 'Update',
  ALT_BLUETICK: 'BlueTick',
  ALT_DELETE_ICON: 'Delete icon',
  ALT_CONGRATULATIONS: 'congratulations',
  ALT_CANDIDATE_PROFILE: 'Candidate profile',
  ALT_LOGO: 'Logo',
  ALT_BADGE: 'Badge',
  EARNED_BADGES: 'Earned Badges',
  GIVE_YOUR_ASSESSMENTS_AND_GET_BADGES: 'Take assessment and earn badges',
  ALT_Employer_Logo: 'Employer Logo',
  ALT_OTHER_PAGES: 'Other Pages',
  CHANGE: 'Change',
  DOCX_PDF_FILE_STR: 'docx, pdf, upto 1 MB',
  PNG_JPG_FILE_STR: 'png, jpg, jpeg, upto 100 KB',
  JOB_UPDATED_SUCCESSFULLY: 'Job Updated Successfully',

  PASSWORD_SENT_SUCCESSFULLY: 'Password Sent Successfully',
  PASSWORD_RESET_LINK_SENT_SUCCESSFULLY:
    'Password reset link sent successfully',
  LOGIN: 'Login',
  PASSWORD: 'Password',
  FORGOT_PASSWORD: 'Forgot Password?',
  NEW_TO_COMPANY_IN: 'New to AlignMyCareer?',
  REGISTER_FOR_FREE: 'Register for Free',
  ENTER_PASSWORD: 'Enter password',
  FORGOT_PASSWORD_: 'Forgot Password',
  ENTER_YOUR_REGISTERED_EMAIL: 'Enter your registered email ID',
  SEND: 'Send',
  CHANGE_PASSWORD: 'Change Password',
  NEW_PASSWORD: 'New Password',
  ENTER_NEW_PASSWORD: 'Enter new password',
  SUBMIT: 'Submit',
  REGISTER: 'Register',
  FULL_NAME_COMPANY_NAME: 'Full name / Company name',
  ENTER_EMAIL: 'Enter email',
  PHONE_NUMBER: 'Phone number',
  ENTER_PHONE_NUMBER: 'Enter phone number',
  ROLE: 'Role',
  ROLE_PLACEHOLDER: 'HR Manager, Project Manager, CEO etc',
  USER_AGREEMENT: 'User Agreement',
  PRIVACY_POLICY: 'Privacy Policy',
  AND: 'and',
  TERM_AND_CONDITIONS: 'Terms & Conditions.',
  ALREADY_ON_COMPANY_IN: 'Already on AlignMyCareer?',
  BY_CLICKING_AGREE_JOIN_YOU_AGREE_TO_THE_COMPANY_IN:
    'By clicking Register, you agree to our', //  TBD
  CONFIRM_TOKEN_REDIRECT_PAGE: 'Confirm Token Redirect Page',
  INVALID_REGISTRATION_TOKEN: 'Invalid Registration token',
  RESEND_TOKEN: 'Resend Token',
  YOUR_OLD_TOKEN:
    'Your old Token has expired, please check your email for the new token link',
  OLD_PASSWORD: 'Old Password',
  ENTER_OLD_PASSWORD: 'Enter old password',
  RESEND_EMAIL: 'Resend Email',
  ENTER_YOUR_REGISTER_EMAIL: 'Enter your registered email ID',
  PASSWORD_SEND_SUCCESSFULLY: 'Password sent Successfully',
  PLEASE_CHECK_REGISTERED_EMAIL_ADDRESS: 'Please check your email',
  RESEND_RESET_PASSWORD_LINK: 'Resend reset password link',
  CONFIRM_EMAIL_SUCCESSFULL: 'Email confirmation successful',
  YOUR_EMAIL_ID_IS_REGISTERD: 'Your email registered successfully',
  NOW_CLICK_GOING_TO_LOGIN_SECTION: 'Click to',
  PLEASE_VERIFY_YOUR_EMAIL: 'Please verify your email',
  ONCE_YOU_VERIFY_YOUR_EMAIL_ADDRESS:
    'After verification of email, you are all set to explore',
  RESEND_REGISTRATION_MAIL_SUCCESSFUL: 'Resend Registration email successful',
  DIDNT_RECEIVE_AN_EMAIL: "Didn't receive an email?",

  //  Feedback Form
  FEEDBACK_FORM: 'Feedback form',
  COMMENTS: 'Comments',
  COMMENTS_PLACEHOLDER: 'Enter your comments',

  //  Login

  //  My candidates
  ALL: 'All',
  AVAILABILITY: 'Availability',
  //  candidate View Components
  FROM_TO: 'From-to',
  ROLES: 'Roles',

  MONTH: 'month',
  DAY: 'day',
  MY: 'My',
  MY_COMPANY_NAME: 'AlignMyCareer',
  ALL_RIGHT_RESERVED: 'All rights reserved',
  //  Header Navbar
  FIND_TALENT: 'Find Talent',
  FIND_JOBS: 'Find Jobs',
  MY_CANDIDATES: 'My Candidates',
  MY_JOBS: 'My Jobs',
  MY_PROFILE_ACTIVITY: 'My Profile Activity',
  //  Home page
  SEARCH: 'Search',
  REMARK: 'Remark',
  REMARK_PLACEHOLDER: 'Enter the candidate remark',
  //  Footer
  JOB_SEEKER: 'Job Seeker',
  EMPLOYER: 'Employer',
  SOCIAL: 'Social',
  FIND_JOB: 'Find Job',
  TOKEN_NOT_VALID: 'Oops! Token is not valid',
  EXPIRED_TOKEN: 'Oops! Token is expired',
  FEEDBACK: 'Feedback',
  GENERATE_NEW_TOKEN: 'Generate new Token',

  // Password Reset Forgot Password

  PASSWORD_RESET_ATTEMPTS_EXCEEDED: 'Password reset attempts exceeded',
  USER_NOT_FOUND: 'User not Found',
  REMOVE_LOGO: 'Remove Logo',
  NO_MATCHING_RESULT_FOUND: 'No Matching Result Found...',
  CHANGE_YOUR_PREFERENCES: 'Change your preferences',
  NO_RESULT_FOUND: 'No result found',

  // For badges table

  EXPERT: 'Expert',
  PROFICIENT: 'Proficient',
  INTERMEDIATE: 'Intermediate',
  BEGINNER: 'Beginner',
};

export default UI;
